This Notebook is based on this notebook: https://colab.research.google.com/drive/1_zJMGJnX3XJx7FCHD04SC3Y0KCMdDGMz#scrollTo=chBHYxkg4hFp

In [23]:
import pickle
import pandas as pd
import numpy as np
import astropy
import sunpy
from utils.data_loader import find_repo_root
from pathlib import Path
from sunpy.time import parse_time
import matplotlib.pyplot as plt
import seaborn as sns
#make figures bigger
plt.rcParams["figure.figsize"] = (10,5)

In [24]:
url='https://helioforecast.space/static/sync/icmecat/HELIO4CAST_ICMECAT_v23.csv'
ic=pd.read_csv(url)
ic=ic.drop(columns='Unnamed: 0') #drop an extra index column
# download the full dataset
ic.to_csv(find_repo_root() / Path('Dataset\\Dataset_ICMECAT\\HELIO4CAST_ICMECAT_v23.csv'),index=False) #save to local

In [25]:
ic[ic.isna().any(axis=1)] #check for missing values

,icmecat_id,sc_insitu,icme_start_time,mo_start_time,mo_end_time,mo_sc_heliodistance,mo_sc_long_heeq,mo_sc_lat_heeq,icme_duration,icme_bmax,...,mo_density_mean,mo_density_std,mo_temperature_mean,mo_temperature_std,sheath_speed_mean,sheath_speed_std,sheath_density_mean,sheath_density_std,sheath_pdyn_mean,sheath_pdyn_std
0,ICME_STEREO_A_MOESTL_20250810_01,STEREO-A,2025-08-10T05:17Z,2025-08-10T13:07Z,2025-08-11T08:20Z,0.9587,44.72,7.02,27.05,21.3,...,0.7,0.3,0.0,0.0,658.5,121.2,0.8,0.3,0.6,0.1
1,ICME_Wind_MOESTL_20250726_01,Wind,2025-07-26T16:44Z,2025-07-26T16:44Z,2025-07-27T17:40Z,1.0053,0.22,5.40,24.93,11.1,...,3.0,1.7,36039.7,24287.4,NaN,NaN,NaN,NaN,NaN,NaN
2,ICME_STEREO_A_MOESTL_20250717_01,STEREO-A,2025-07-17T12:46Z,2025-07-17T20:01Z,2025-07-18T04:09Z,0.9563,42.24,7.28,15.38,13.6,...,0.4,0.1,0.0,0.0,631.4,127.4,0.4,0.3,0.2,0.1
3,ICME_STEREO_A_MOESTL_20250705_01,STEREO-A,2025-07-05T19:56Z,2025-07-06T10:51Z,2025-07-07T02:09Z,0.9555,40.94,6.90,30.22,23.9,...,0.5,0.2,0.0,0.0,408.1,81.1,2.0,0.9,0.5,0.3
5,ICME_STEREO_A_MOESTL_20250622_02,STEREO-A,2025-06-22T04:57Z,2025-06-22T04:57Z,2025-06-22T13:56Z,0.9547,39.29,6.01,8.98,8.2,...,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1971,ICME_ULY_RICHARDSON_19910305_01,ULYSSES,1991-03-05T00:00Z,1991-03-05T00:00Z,1991-03-08T20:00Z,2.2833,-41.33,-3.42,92.00,4.7,...,1.3,1.1,25501.7,11677.5,NaN,NaN,NaN,NaN,NaN,NaN
1972,ICME_ULY_RICHARDSON_19910226_01,ULYSSES,1991-02-26T22:00Z,1991-02-26T22:00Z,1991-02-27T17:00Z,2.2166,-36.80,-3.26,19.00,4.7,...,0.9,0.4,65951.4,24933.2,NaN,NaN,NaN,NaN,NaN,NaN
1973,ICME_ULY_RICHARDSON_19910116_01,ULYSSES,1991-01-16T16:00Z,1991-01-16T16:00Z,1991-01-18T11:00Z,1.7583,-9.09,-1.75,43.00,3.1,...,0.9,0.1,55306.4,21032.7,NaN,NaN,NaN,NaN,NaN,NaN
1974,ICME_ULY_RICHARDSON_19901225_01,ULYSSES,1990-12-25T14:00Z,1990-12-25T14:00Z,1990-12-28T12:00Z,1.5160,2.18,-0.49,70.00,5.4,...,1.8,1.1,52144.3,36250.8,NaN,NaN,NaN,NaN,NaN,NaN
1975,ICME_ULY_RICHARDSON_19901211_01,ULYSSES,1990-12-11T04:00Z,1990-12-11T04:00Z,1990-12-14T00:00Z,1.3653,7.38,0.59,68.00,6.4,...,2.5,0.9,52842.0,51226.0,NaN,NaN,NaN,NaN,NaN,NaN

In [26]:
print(ic.keys())
ic.head()

Index(['icmecat_id', 'sc_insitu', 'icme_start_time', 'mo_start_time',
       'mo_end_time', 'mo_sc_heliodistance', 'mo_sc_long_heeq',
       'mo_sc_lat_heeq', 'icme_duration', 'icme_bmax', 'icme_bmean',
       'icme_bstd', 'icme_speed_mean', 'icme_speed_std', 'mo_duration',
       'mo_bmax', 'mo_bmean', 'mo_bstd', 'mo_bzmean', 'mo_bzmin', 'mo_bzstd',
       'mo_bymean', 'mo_bystd', 'mo_speed_mean', 'mo_speed_std',
       'mo_expansion_speed', 'mo_pdyn_mean', 'mo_pdyn_std', 'mo_density_mean',
       'mo_density_std', 'mo_temperature_mean', 'mo_temperature_std',
       'sheath_speed_mean', 'sheath_speed_std', 'sheath_density_mean',
       'sheath_density_std', 'sheath_pdyn_mean', 'sheath_pdyn_std'],
      dtype='object')

,icmecat_id,sc_insitu,icme_start_time,mo_start_time,mo_end_time,mo_sc_heliodistance,mo_sc_long_heeq,mo_sc_lat_heeq,icme_duration,icme_bmax,...,mo_density_mean,mo_density_std,mo_temperature_mean,mo_temperature_std,sheath_speed_mean,sheath_speed_std,sheath_density_mean,sheath_density_std,sheath_pdyn_mean,sheath_pdyn_std
0,ICME_STEREO_A_MOESTL_20250810_01,STEREO-A,2025-08-10T05:17Z,2025-08-10T13:07Z,2025-08-11T08:20Z,0.9587,44.72,7.02,27.05,21.3,...,0.7,0.3,0.0,0.0,658.5,121.2,0.8,0.3,0.6,0.1
1,ICME_Wind_MOESTL_20250726_01,Wind,2025-07-26T16:44Z,2025-07-26T16:44Z,2025-07-27T17:40Z,1.0053,0.22,5.40,24.93,11.1,...,3.0,1.7,36039.7,24287.4,NaN,NaN,NaN,NaN,NaN,NaN
2,ICME_STEREO_A_MOESTL_20250717_01,STEREO-A,2025-07-17T12:46Z,2025-07-17T20:01Z,2025-07-18T04:09Z,0.9563,42.24,7.28,15.38,13.6,...,0.4,0.1,0.0,0.0,631.4,127.4,0.4,0.3,0.2,0.1
3,ICME_STEREO_A_MOESTL_20250705_01,STEREO-A,2025-07-05T19:56Z,2025-07-06T10:51Z,2025-07-07T02:09Z,0.9555,40.94,6.90,30.22,23.9,...,0.5,0.2,0.0,0.0,408.1,81.1,2.0,0.9,0.5,0.3
4,ICME_Wind_MOESTL_20250703_01,Wind,2025-07-03T04:52Z,2025-07-03T12:34Z,2025-07-04T19:06Z,1.0054,0.07,3.18,38.23,14.3,...,8.0,4.9,63561.2,37658.7,375.4,11.4,26.4,11.4,6.3,2.9

In [27]:
# list all unique values in the sc_insitu column
print(ic['sc_insitu'].unique())

['STEREO-A' 'Wind' 'SolarOrbiter' 'PSP' 'BepiColombo' 'MAVEN' 'Juno'
 'MESSENGER' 'VEX' 'STEREO-B' 'ULYSSES']

# Convert Spacecraft coordinates from HEEQ to GSE

In [28]:
print(ic[['mo_start_time', 'mo_sc_heliodistance', 'mo_sc_long_heeq', 'mo_sc_lat_heeq']].head())

       mo_start_time  mo_sc_heliodistance  mo_sc_long_heeq  mo_sc_lat_heeq
0  2025-08-10T13:07Z               0.9587            44.72            7.02
1  2025-07-26T16:44Z               1.0053             0.22            5.40
2  2025-07-17T20:01Z               0.9563            42.24            7.28
3  2025-07-06T10:51Z               0.9555            40.94            6.90
4  2025-07-03T12:34Z               1.0054             0.07            3.18

In [29]:
import pandas as pd
import numpy as np
from astropy.time import Time
from astropy.coordinates import SkyCoord
import sunpy.coordinates
from sunpy.coordinates import frames
from astropy import units as u

# Convert to datetime
ic['sc_time'] = pd.to_datetime(ic['mo_start_time']).dt.tz_convert(None)
times = Time(ic['sc_time'].values)
# also convert these even though they are not used here
ic['icme_start_time'] = pd.to_datetime(ic['icme_start_time']).dt.tz_convert(None)
ic['mo_start_time'] = pd.to_datetime(ic['mo_start_time']).dt.tz_convert(None)
ic['mo_end_time'] = pd.to_datetime(ic['mo_end_time']).dt.tz_convert(None)

# spherical HEEQ (r, lon, lat)
r = ic['mo_sc_heliodistance'].values * u.AU
lon = ic['mo_sc_long_heeq'].values * u.deg
lat = ic['mo_sc_lat_heeq'].values * u.deg

# Define HEEQ using HeliographicStonyhurst
# see https://docs.sunpy.org/en/stable/reference/coordinates/index.html for reference
heeq = SkyCoord(
    lon=lon,
    lat=lat,
    radius=r,
    frame=frames.HeliographicStonyhurst,
    obstime=times,
    representation_type='spherical'
)

# Convert to GSE
gse = heeq.transform_to(frames.GeocentricSolarEcliptic(obstime=times))
gse_cartesian = gse.cartesian

# Extract in Earth radii
x_gse_RE = gse_cartesian.x.to(u.R_earth).value
y_gse_RE = gse_cartesian.y.to(u.R_earth).value
z_gse_RE = gse_cartesian.z.to(u.R_earth).value

# Store in DataFrame
ic['mo_sc_GSE_x'] = x_gse_RE
ic['mo_sc_GSE_y'] = y_gse_RE
ic['mo_sc_GSE_z'] = z_gse_RE

# Preview the result
print(ic[['sc_time', 'mo_sc_GSE_x', 'mo_sc_GSE_y', 'mo_sc_GSE_z']].head())

              sc_time  mo_sc_GSE_x   mo_sc_GSE_y  mo_sc_GSE_z
0 2025-08-10 13:07:00  7707.426747 -15733.101831    26.259811
1 2025-07-26 16:44:00   241.415368    -90.824942     4.230704
2 2025-07-17 20:01:00  7189.928883 -15033.024711    42.383621
3 2025-07-06 10:51:00  6906.444262 -14674.672898    43.655766
4 2025-07-03 12:34:00   263.738137    -30.264605    11.431687

# Save to .csv

In [30]:
# save the data to a csv file based on the sc_insitu values ('Wind')
filtered_ic = ic[(ic['sc_insitu'] == 'Wind')]
filtered_ic.to_csv(find_repo_root() / Path('Dataset\\Dataset_ICMECAT\\helio4cast_icmecat_Wind.csv'), index=False)

Resize to time range of GFOC

In [31]:
import pandas as pd

filtered_ic = pd.read_csv(find_repo_root() / Path('Dataset\\Dataset_ICMECAT\\helio4cast_icmecat.csv'))

GFOC_start = pd.to_datetime('2023-01-01 00:00:00')
GFOC_end = pd.to_datetime('2025-01-01 00:00:00')

# only select times that are in the range of the GFOC data
ic_GFOC = filtered_ic[pd.to_datetime(filtered_ic['mo_end_time'], format='%Y-%m-%d %H:%M:%S') >= GFOC_start]
ic_GFOC = ic_GFOC[pd.to_datetime(ic_GFOC['icme_start_time'], format='%Y-%m-%d %H:%M:%S') <= GFOC_end]

# save the modified DataFrame to a new CSV file
ic_GFOC.to_csv(find_repo_root() / Path('Dataset\\Dataset_ICMECAT\\helio4cast_icmecat_GFOC.csv'), index=False)